SELECT * FROM AIRBNB_DB.DWH.DIM_HOST;
SELECT * FROM AIRBNB_DB.DWH.DIM_LOCATION;
SELECT * FROM AIRBNB_DB.DWH.DIM_PROPERTY;
SELECT * FROM AIRBNB_DB.DWH.DIM_REVIEWS;
SELECT * FROM AIRBNB_DB.DWH.DIM_DATE;



SELECT * FROM AIRBNB_DB.DWH.AIRBNBFACT;
SELECT COUNT(*) FROM AIRBNB_DB.DWH.AIRBNBFACT;


-- =========================
-- BACKUP FACT TABLE
-- =========================
CREATE TABLE AIRBNBFACT_BACKUP AS
SELECT * FROM AIRBNB_DB.DWH.AIRBNBFACT;

-- =========================
-- REMOVE DUPLICATES
-- =========================
CREATE OR REPLACE TABLE AIRBNB_DB.DWH.AIRBNBFACT AS
SELECT *
FROM AIRBNB_DB.DWH.AIRBNBFACT
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        Date_SK,
        Host_SK,
        Location_SK,
        Property_SK
    ORDER BY Review_SK DESC
) = 1;



-- =========================
-- NEEDED Info to Connect with dbt
-- =========================
SELECT LOWER(CURRENT_REGION()), LOWER(CURRENT_ACCOUNT());

